### ISSUE TITLE
hallowelt.py does not work with python2

### ISSUE THREAD

**Issue by jnweiger** [PythonUserGroupNuernberg/BeginnerWorkshop#1]
import tkinter leads to an error on Ubuntu with python-2.7.6:

<pre>
File "hallowelt.py", line 1, in <module>
    import tkinter 
ImportError: No module named tkinter
</pre>

apt install python-tk python3-tk

With python2 the module is called Tkinter instead.

**Comment by benk2x** [comment]
its done and save under _2.7_hallowelt.py
